Use new msixvcdl API

diff --git a/.github/workflows/decrypt-msixvc.yml b/.github/workflows/decrypt-msixvc.yml
--- a/.github/workflows/decrypt-msixvc.yml
+++ b/.github/workflows/decrypt-msixvc.yml
@@ -11,7 +11,7 @@ jobs:
   decrypt:
     runs-on: ubuntu-latest
     env:
-      PRODUCTS_URL: https://displaycatalog.mp.microsoft.com/v7.0/products?bigIds=9PMF91N3LZ3M&market=US&languages=en-US,neutral&MS-CV=DGU1mcuYo0WMMp+F.1
+      PRODUCTS_ID: 9PMF91N3LZ3M
 
     steps:
       - name: Checkout repository
@@ -19,6 +19,8 @@ jobs:
 
       - name: Download products.json
         run: |
+          PRODUCTS_URL="https://displaycatalog.mp.microsoft.com/v7.0/products?bigIds=${PRODUCTS_ID}&market=US&languages=en-US,neutral&MS-CV=DGU1mcuYo0WMMp+F.1"
+          echo "PRODUCTS_URL=$PRODUCTS_URL" >> $GITHUB_ENV
           curl -sSL "$PRODUCTS_URL" -o products.json
           cat products.json
 
@@ -46,27 +48,17 @@ jobs:
             echo "latest_last_update=none" >> "$GITHUB_OUTPUT"
           fi
 
-      - name: Get download URL from MsixvcPackageDownloader
+      - name: Get download URL from msixvcdl-expressjs
         id: apicall
         if: steps.extract.outputs.lastUpdateDate != steps.get_latest.outputs.latest_last_update
         env:
-          PUSH_KEY: ${{ secrets.SECRET_POST_TOKEN }}
+          POST_KEY: ${{ secrets.SECRET_POST_TOKEN }}
         run: |
-          curl -sSL "https://github.com/Yakov5776/MsixvcPackageDownloader/releases/download/release-v1.5/linux-x64-build.zip" -o MsixvcPackageDownloader.zip
-          unzip -q MsixvcPackageDownloader.zip
-          chmod +x MsixvcPackageDownloader
-          cat << 'EOF' > token.json
-          ${{ secrets.MS_TOKEN }}
-          EOF
-          
-          msixvc_url=$(./MsixvcPackageDownloader ${{ steps.extract.outputs.contentId }})
+          msixvc_req=$(curl -sSL -X GET "https://msixvc.yakov.cloud/msixvc/$PRODUCTS_ID" -H "Authorization: Bearer $POST_KEY")
+          msixvc_url=$(echo "$msixvc_req" | jq -r '.files[0].url')
           if [ -z "$msixvc_url" ]; then
-            echo "MsixvcPackageDownloader failed, trying to refresh token..."
-            auth_json=$(curl -sSL -X POST "${{ secrets.SECRET_POST_URL }}?mode=refresh" -H "x-access-key: $PUSH_KEY")
-            auth_url=$(echo "$auth_json" | jq -r '.authUrl')
-            echo "$auth_url" > authUrl.txt
-            echo "Retrying MsixvcPackageDownloader with refreshed token..."
-            msixvc_url=$(./MsixvcPackageDownloader ${{ steps.extract.outputs.contentId }})
+            echo "Error: No XVC URL found"
+            exit 1
           fi
 
           filename=$(basename "$msixvc_url")
@@ -77,22 +69,6 @@ jobs:
           echo "filename=$filename" >> $GITHUB_ENV
           echo "decryptedName=$decryptedName" >> $GITHUB_ENV
           echo "releaseName=$releaseName" >> $GITHUB_ENV
-
-      - name: Update MS_TOKEN secret
-        if: steps.extract.outputs.lastUpdateDate != steps.get_latest.outputs.latest_last_update
-        env:
-          UPDATE_URL:  ${{ secrets.SECRET_POST_URL }}
-          PUSH_KEY: ${{ secrets.SECRET_POST_TOKEN }}
-        run: |
-          NEW_TOKEN=$(cat token.json)
-          ENCODED_VALUE=$(echo -n "$NEW_TOKEN" | base64)
-
-          curl -X POST "$UPDATE_URL" \
-            -H "Content-Type: application/json" \
-            -H "x-access-key: $PUSH_KEY" \
-            -d @- << EOF
-          {"value": "$ENCODED_VALUE"}
-          EOF
 
       - name: Check if tag already exists
         id: tagcheck
